services:
  - type: worker
    name: duplicate-check-bot
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SESSION
        sync: false
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: MONGO_URI
        sync: false
      - key: LOG_CHANNEL
        sync: false
